name: Action Basics Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo String
        run: echo "Welcome to GitHub Actions!"

      - name: Use a Marketplace Action
        # A pre-built public action that prints a greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Agile Student" # Input passed to the action

      - name: Run a Multi-line Script
        run: |
          echo "---"
          echo "This is a multi-line shell script."
          echo "The current runner OS is: $(uname -a)"
          echo "---"
